### ISSUE TITLE
Add support for MangaUpdates

### ISSUE THREAD

**Issue by LadyHaywood** [naoka-dev/Naoka#185]
Allowing MangaUpdates as one of the account connections.

This is more of a question, but would it be possible to add MangaDex as a connection as well or is that not doable because you can't export your MangaDex library?

**Comment by Nekidev** [comment]
Hello! First of all, this project is pretty much paused atm, but yeah it's planned for a future version.

Also, I was planning to overall rewrite yhe app from scratch with better documentation and an API server of it's own to be able to download the complete media database with better support for synchronization with providers.

I don't really have an ETA of when I'll continue working on this, but I also rebuilt the project like a week ago on my laptop and there were bugs everywhere so im probably gonna be trying to rewrite the app from scratch with a better UI and an API server, as I said before.
